Adyen/adyen-commercetools

extension/README.md
extension/resources/payment-custom-types.json
extension/src/api/payment/payment.controller.js
extension/src/config/init/initPaymentCustomType.js
extension/src/paymentHandler/kcp/kcpMakePayment.handler.js
extension/test/integration/kcpMakePayment.spec.js
extension/test/resources/payment-credit-card-3d.json
extension/test/resources/payment-credit-card.json
extension/test/resources/payment-kcp.json
extension/test/resources/payment-no-method.json
extension/test/resources/payment-paypal.json

Part of https://github.com/commercetools/commercetools-adyen-integration/issues/21
I implemented only first step as this is as far as I could get for KCP. In this step, I got redirect URL.
Boy-scout change: I group all the payment custom types into 1.

21 kcp - first step

---

cypress.json
extension/src/api/health/health.controller.js
extension/src/api/payment/payment.controller.js
extension/src/paymentHandler/creditCard/creditCard.handler.js
extension/src/paymentHandler/creditCard/creditCardCompletePayment.handler.js
extension/src/paymentHandler/creditCard/creditCardMakePayment.handler.js
extension/src/paymentHandler/fetchPaymentMethod.handler.js
extension/src/paymentHandler/kcp/kcpMakePayment.handler.js
extension/src/paymentHandler/kcp/kcpPayment.handler.js
extension/src/paymentHandler/paypal/paypal.handler.js
extension/src/paymentHandler/paypal/paypalCompletePayment.handler.js
extension/src/paymentHandler/paypal/paypalMakePayment.handler.js
extension/src/routes.js
extension/src/validator/errorMessages.js
extension/src/validator/validator.js
extension/src/validator/validatorBuilder.js
extension/test/resources/ctp-payment.json
extension/test/unit/payment.controller.spec.js
package-lock.json
package.json

Fixes: https://github.com/commercetools/commercetools-adyen-integration/issues/14

14 error handling

---

notification/resources/adyen-events.json
notification/test/unit/notification.handler.spec.js

Add missing notification event codes:
https://docs.adyen.com/developers/development-resources/notifications/event-codes

add missing notification event codes

---

extension/docs/IntegrationGuide.md
extension/src/config/config.js
extension/src/init.js
notification/docs/DevelopmentGuide.md
notification/docs/IntegrationGuide.md
notification/src/config/config.js
notification/src/init.js

Add possibility to set keep alive timeout

---

extension/package-lock.json
extension/package.json
extension/src/api/payment/payment.controller.js

Error in the extension module:
```
jsonPayload: {
err: {
message:  "Unexpected token , in JSON at position 13640"    
name:  "SyntaxError"    
stack:  "SyntaxError: Unexpected token , in JSON at position 13640
at JSON.parse (<anonymous>)
at _getPaymentObject (/app/src/api/payment/payment.controller.js:50:28)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)"    
}
hostname:  "ctp-adyen-integration-service-extension-5c8dff8ff8-8pddz"   
level:  50   
msg:  "Unexpected error when processing URL {"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":null,"pathname":"/","path":"/","href":"/"}"   
name:  "ctp-adyen-integration-extension"   
pid:  16   
v:  0   
}
```

Log JSON received from the CTP

---

extension/package-lock.json
extension/package.json
notification/package-lock.json
notification/package.json

Tests are failing because of ngrok tunnel problems:
```
{
"details": {
"err": "a successful ngrok tunnel session has not yet been established"
}
"error_code": 104
"msg": "ngrok is not yet ready to start tunnels"
"status_code": 503
}
```
I will wait and then try to restart.

76 update dependencies

---

extension/README.md
notification/README.md

Add docker pulls badges 🚀

---

.dependabot/config.yml

Automate dependabot PRs merging.

Automate dependabot PRs merging.

---

extension/package-lock.json
extension/package.json
notification/package-lock.json
notification/package.json

This is now possible after upgrading the nodejs version from 8 to 12.

bump @commercetools/sdk-middleware-http from 5.2.1 to 6.0.4

---

extension/docs/ManualCapture.md
extension/resources/web-components-payment-type.json
extension/src/config/constants.js
extension/src/paymentHandler/manual-capture.handler.js
extension/src/paymentHandler/payment-handler.js
extension/src/paymentHandler/payment-utils.js
extension/src/service/web-component-service.js
extension/src/validator/error-messages.js
extension/src/validator/validator-builder.js
extension/test/e2e/e2e-test-utils.js
extension/test/e2e/klarna.spec.js
extension/test/integration/manual-capture.spec.js
extension/test/unit/manual-capture.handler.spec.js
extension/test/unit/validator-builder.spec.js

Fixes: https://github.com/commercetools/commercetools-adyen-integration/issues/340

#340 use transaction for manual capturing

---

extension/package-lock.json
extension/package.json
extension/src/ctp.js
extension/src/ctp/ctp-client.js
extension/src/init.js
extension/src/paymentHandler/klarna-make-payment.handler.js
extension/test/cleanup-ctp-project.js
extension/test/e2e/credit-card-3ds-native.spec.js
extension/test/e2e/credit-card-3ds-redirect.spec.js
extension/test/e2e/credit-card.spec.js
extension/test/e2e/klarna.spec.js
extension/test/integration/cancel-or-refund.handler.spec.js
extension/test/integration/get-origin-keys.handler.spec.js
extension/test/integration/get-payment-methods.handler.spec.js
extension/test/integration/klarna-make-payment.spec.js
extension/test/integration/make-payment.handler.spec.js
extension/test/integration/manual-capture.spec.js
notification/package-lock.json
notification/package.json
notification/src/utils/ctp.js

#389 
Will look like as below:

#389 Add user agent middleware.

---

extension/src/api/payment/payment.controller.js
notification/src/handler/notification/notification.handler.js

Since version 5.0.0 serialize-error provides 2 methods:
- serializeError
- deserializeError

Fix serialize-error package import

---

extension/test/e2e/pageObjects/KlarnaPage.js
notification/src/handler/notification/notification.handler.js

Klarna has changed their UI, so I updated our e2e test.

Small fixes

---

extension/test/e2e/pageObjects/KlarnaPage.js

Klarna test was failing because some HTML elements are not present anymore on the page.

Fix test for klarna

---

notification/src/handler/notification/notification.handler.js
notification/src/utils/hmacValidator.js
notification/test/unit/hmac-verification.spec.js

Fixes: https://github.com/commercetools/commercetools-adyen-integration/issues/407

#407 Improve error logging for hmac validations

---

extension/docs/WebComponentsIntegrationGuide.md
extension/src/service/web-component-service.js
extension/test/integration/get-origin-keys.handler.spec.js
extension/test/integration/get-payment-methods.handler.spec.js

Fixes: https://github.com/commercetools/commercetools-adyen-integration/issues/466

#466 add application info to the requests

---

extension/docs/Refund.md
extension/src/config/constants.js
extension/src/paymentHandler/payment-handler.js
extension/src/paymentHandler/payment-utils.js
extension/src/paymentHandler/refund-payment.handler.js
extension/src/service/web-component-service.js
extension/test/integration/refund-payment.handler.spec.js

In this PR, I added a refund endpoint to the Adyen integration.
TODO:
**What won't be included in this PR**
Updating the notification module - this will be done in a different PR. It means that this feature is not fully functional yet.
Part of the issue: https://github.com/commercetools/commercetools-adyen-integration/issues/399
After the endpoint is called with the following payment, refunds were made on Adyen:
```json
{
"key": "14",
"amountPlanned": {
"type": "centPrecision",
"currencyCode": "EUR",
"centAmount": 1000,
"fractionDigits": 2
},
"paymentMethodInfo": {
"paymentInterface": "ctp-adyen-integration"
},
"transactions": [
{
"id": "3d4f784b-0e7e-489b-a52d-8b83515c4be6",
"type": "Authorization",
"amount": {
"type": "centPrecision",
"currencyCode": "EUR",
"centAmount": 1000, …
```

#399 add refund endpoint

---

extension/src/paymentHandler/cancel-payment.handler.js
extension/src/paymentHandler/refund-payment.handler.js
notification/.eslintrc
notification/docs/IntegrationGuide.md
notification/src/handler/notification/notification.handler.js
notification/src/utils/hmacValidator.js
notification/test/integration/notification.handler.spec.js
notification/test/resources/notification-refund-fail.json
notification/test/resources/payment-draft.json
notification/test/unit/notification.handler.spec.js

#399 notification module - get matching transactions by interactionId

---

extension/package-lock.json
extension/package.json
extension/test/e2e/credit-card-3ds-native.spec.js
extension/test/e2e/credit-card-3ds-redirect.spec.js
extension/test/e2e/credit-card.spec.js
extension/test/e2e/e2e-test-utils.js
extension/test/e2e/klarna.spec.js
notification/package-lock.json
notification/package.json

use basic nodejs http server to server static file content, instead of using vulnerable `node-static` dependency.

---

extension/package-lock.json
extension/package.json
extension/src/paymentHandler/refund-payment.handler.js
extension/test/e2e/credit-card-3ds-native.spec.js
extension/test/e2e/credit-card-3ds-redirect.spec.js
extension/test/e2e/credit-card.spec.js
extension/test/e2e/e2e-test-utils.js
extension/test/e2e/klarna.spec.js
extension/test/test-utils.js
notification/package-lock.json
notification/package.json
notification/src/handler/notification/notification.handler.js
notification/test/test-utils.js

* https://www.npmjs.com/package/p-map
Fixes: #16

Replace bluebird Promise.map

---

README.md

Fix #55 - Add PSI DSS note to README.md

---

extension/docs/WebComponentsIntegrationGuide.md
notification/docs/DevelopmentGuide.md
notification/docs/IntegrationGuide.md

Fixes: https://github.com/commercetools/commercetools-adyen-integration/issues/509

Fix broken links in the documentations

---

.github/workflows/ci.yml
extension/test/e2e/pageObjects/KlarnaPage.js

Turnstyle docs: https://github.com/softprops/turnstyle#inputs

Add turnstyle option to limit concurrent runs in different branches

---

extension/src/init.js
extension/test/e2e/klarna.spec.js
extension/test/integration/integration-test-set-up.js
extension/test/integration/klarna-make-payment.spec.js
extension/test/integration/make-payment.handler.spec.js

Add multitenancy integration test scenarios for extension module

---

extension/docs/WebComponentsIntegrationGuide.md

Inspired from the official document: https://docs.adyen.com/online-payments/components-web#step-3-make-a-payment
Addresses: #622

Add section to integration document for additional `makePaymentRequest` parameters.

---

extension/package-lock.json
extension/package.json
notification/index.googleFunction.js
notification/index.lambda.js
notification/package.json
notification/src/api/notification/notification.controller.js
notification/src/handler/notification/notification.handler.js
notification/src/utils/parser.js
notification/test/unit/lambda.spec.js
notification/test/unit/notification.controller.spec.js
notification/test/unit/notification.handler.spec.js

Fix "metadata.commercetoolsProjectKey" check and also return "accepted" by default.

---

extension/docs/WebComponentsIntegrationGuide.md

Add more details on integration doc for the refusal case.

---

extension/package-lock.json
extension/package.json
notification/package-lock.json
notification/package.json

Release Note
Fixes:
Modify the error handling to avoid returning stacktrace when user accesses extension module URL through browser

Upgrade version to v7.1.2

---

.github/workflows/ci.yml
extension/docs/HowToRun.md
notification/docs/HowToRun.md

Change node 12 to node 14 in various documents

Modify node version in various documents

---

extension/package-lock.json
extension/package.json
extension/src/service/web-component-service.js
notification/package-lock.json
notification/package.json

Co-authored-by: Fifciuu <fjedrasik@vuestorefront.io>

fix: paypal through v67 adyen api (#659)

---

extension/index.googleFunction.js
extension/index.lambda.js
extension/src/api/payment/payment.controller.js
extension/src/paymentHandler/payment-handler.js
extension/src/utils.js
extension/src/validator/validator-builder.js
extension/test/integration/fixtures/ctp-payment.json
extension/test/unit/google-function.spec.js
extension/test/unit/lambda.spec.js
extension/test/unit/payment-handler-authorization.spec.js
extension/test/unit/payment-handler.spec.js
extension/test/unit/payment.controller.spec.js
extension/test/unit/validator-builder.spec.js

- Remove data attribute inside the JSON object returning from payment handler https://github.com/commercetools/commercetools-adyen-integration/pull/630#discussion_r600740392
Original
```
{
success : true,
data : {
actions : [ { ... } ]   
}
}
```
```
{
success : false,
data : {
errors : [ { ... } ]   
}
}
```
Now
```
{
success : true,
actions : [ { ... } ]
}
```
```
{
success : false,
errors : [ { ... } ]
}
```
- Modify payment controller
- Update corresponding integration test / unit test

Remove json data attribute

---

extension/docs/HowToRun.md
extension/package-lock.json
extension/package.json
notification/docs/HowToRun.md
notification/package-lock.json
notification/package.json

Document minimum required scopes for the modules.

---

notification/src/api/notification/notification.controller.js
notification/src/utils/error-utils.js
notification/src/utils/logger.js

Handle unexpected errors by returning VError.
Related Issue: https://github.com/commercetools/commercetools-adyen-integration/issues/813

Handling unexpected errors with VError.

---

extension/package-lock.json
extension/package.json
notification/package-lock.json
notification/package.json

- Update version number from v9.0.3 to v9.0.4 in package.json

Update version number

---

extension/docs/HowToRun.md
extension/package-lock.json
extension/package.json
extension/src/config/config.js
extension/test/unit/config/config.spec.js
notification/package-lock.json
notification/package.json

I updated Adyen API URL in this PR.

Update adyen api version to v68

---

notification/docs/IntegrationGuide.md

Documentation change, extension was written where notification should be.

doc: change to notification

---

extension/test/e2e/pageObjects/AffirmPage.js
extension/test/test-utils.js

The cause was probably because a new screen was added to the flow.

Fix affirm test

---

extension/test/e2e/klarna.spec.js
extension/test/e2e/pageObjects/KlarnaPage.js

Adapt the new page layout given by Klarna in e2e test

Fix klarna e2e test

---

docs/adr/0007-pre-auth-and-auth-adjustment.md
extension/docs/HowToRun.md
extension/docs/ManualCapture.md
extension/docs/UpdateAmountAndExtendAuthorisation.md
extension/package-lock.json
extension/package.json
extension/resources/web-components-payment-type.json
extension/src/config/constants.js
extension/src/paymentHandler/amount-updates.handler.js
extension/src/paymentHandler/payment-handler.js
extension/src/service/web-component-service.js
extension/src/validator/error-messages.js
extension/src/validator/validator-builder.js
extension/test/integration/amount-updates.handler.spec.js
extension/test/integration/amount-updates.spec.js
extension/test/unit/validator-builder.spec.js
notification/src/utils/parser.js
notification/test/unit/notification.controller.spec.js

Fixes: https://github.com/commercetools/commercetools-adyen-integration/issues/856

Add support for amountUpdates

---

extension/package-lock.json
extension/package.json
extension/test/unit/config/config.spec.js
extension/test/unit/get-payment-methods.handler.spec.js
notification/package-lock.json
notification/package.json
renovate.json

- Upgrade Node-Fetch library to latest version.
- Fix tests which were using stub, Use nock instead.

Update node fetch

---

extension/docs/Refund.md
extension/package-lock.json
extension/package.json
extension/resources/payment-transaction-type.json
extension/src/config/init/ensure-custom-type.js
extension/src/config/init/ensure-resources.js
extension/src/paymentHandler/refund-payment.handler.js
extension/test/unit/config/init/ensure-resources.spec.js
extension/test/unit/refund-payment.handler.spec.js
notification/package-lock.json
notification/package.json

Fixes: https://github.com/commercetools/commercetools-adyen-integration/issues/975

Add custom refund reference

---

extension/docs/ManualCapture.md
extension/package-lock.json
extension/package.json
extension/src/paymentHandler/manual-capture.handler.js
extension/src/service/web-component-service.js
extension/test/unit/manual-capture.handler.spec.js
notification/package-lock.json
notification/package.json

- Add new custom attribute reference for manual capture requests
- Add one unit test to verify the newly added attribute
- Update Manual Capture documentation

Add custom reference field for manual capture 

---

extension/package-lock.json
extension/package.json
notification/package-lock.json
notification/package.json

Change version number to v10.1.1 in package.json

---

extension/test/unit/config/config.spec.js
notification/test/unit/config.spec.js

Fix unit tests when extensionrc and notificationrc files are used for config

---

extension/package-lock.json
extension/package.json
notification/package-lock.json
notification/package.json

Update version number in `extension/package.json` and `notification/package.json` to 11.0.1

Release v11.0.1

---

extension/package-lock.json
extension/package.json
notification/package-lock.json
notification/package.json

Update version number to v11.1.0 in package.json

Release v11.1.0

---

extension/package-lock.json
extension/package.json
notification/package-lock.json
notification/package.json

Update version number in package.json

Update version number in package.json
