- notification/src/api/notification/notification.controller.js
- notification/src/config/config.js
- notification/src/config/init/ensure-interface-interaction-custom-type.js
- notification/src/handler/notification/notification.handler.js
- notification/src/server.js
- notification/src/utils/logger.js
Resolves #52
Not the log looks like this:
```
{
"name": "ctp-adyen-integration-notifications",
"hostname": "local",
"pid": 32801,
"level": 50,
"adyenRequestBody": "{\r\n  \"live\": \"false\",\r\n  \"notificationItems\": [\r\n    {\r\n      \"NotificationRequestItem\": {\r\n        \"additionalData\": {\r\n          \"expiryDate\": \"12\\/2012,\r\n          \" NAME1 \": \"VALUE1\",\r\n          \"authCode\": \"1234\",\r\n          \"cardSummary\": \"7777\",\r\n          \"totalFraudScore\": \"10\",\r\n          \"NAME2\": \"  VALUE2  \",\r\n          \"fraudCheck-6-ShopperIpUsage\": \"10\"\r\n        },\r\n        \"amount\": {\r\n          \"currency\": \"EUR\",\r\n          \"value\": 10100\r\n        },\r\n        \"eventCode\": \"AUTHORISATION\",\r\n        \"eventDate\": …
```
> #52 log the payload received from adyen in case of error

- extension/docs/IntegrationGuide.md
- extension/resources/payment-custom-types.json
- extension/src/api/payment/payment.controller.js
- extension/src/paymentHandler/cancel-or-refund.handler.js
- extension/src/paymentHandler/creditCard/credit-card-make-payment.handler.js
- extension/src/paymentHandler/kcp/kcp-make-payment.handler.js
- extension/src/paymentHandler/paypal/paypal-make-payment.handler.js
- extension/src/validator/error-messages.js
- extension/src/validator/validator-builder.js
- extension/test/fixtures/ctp-payment.json
- extension/test/fixtures/payment-credit-card-3d.json
- extension/test/fixtures/payment-credit-card.json
- extension/test/fixtures/payment-kcp.json
- extension/test/fixtures/payment-no-method.json
- extension/test/fixtures/payment-paypal.json
- extension/test/integration/credit-card-make-payment.handler.spec.js
- extension/test/unit/payment.controller.spec.js
- notification/src/handler/notification/notification.handler.js
- notification/test/integration/init/ensure-payment-custom-type.js
- notification/test/integration/init/init-resources.js
- notification/test/resources/payment-credit-card.json
- notification/test/resources/payment-custom-types.json
- notification/test/resources/payment-draft.json
This resolves #62 
This work should change the reference field from interfaceId to a custom field specified on the payment object. If you could give some feedback on whether this is the correct approach, that'd be great. If you want the name of the field to be different too, I can make that change.
All the unit tests past, one test fails but that seems to be failing on master too right now so it seems to be unrelated.
> Change all interfaceId fields to use custom.fields.merchantReference instead

- extension/src/validator/validator-builder.js
- extension/test/unit/validator-builder.spec.js
Do more checks to ensure the underlying objects exist before checking that the merchantReference field isn't empty
> Fix potential error with merchantReference validation

- extension/docs/DevelopmentAndDeploymentGuide.md
- extension/src/config/config.js
- extension/src/config/init/ensure-resources.js
- notification/docs/DevelopmentGuide.md
- notification/src/config/config.js
- notification/src/config/init/ensure-interface-interaction-custom-type.js
This fixes #72. 
This is based off of the changes in #68. 
Once that PR is merged, this one should follow. This is due to conflicts that would otherwise exist due to changes made in that PR
> Ability to disable ensure resources

- .travis.yml
- extension/src/paymentHandler/payment-utils.js
- extension/test/integration/cancel-or-refund.handler.spec.js
- extension/test/integration/credit-card-make-payment.handler.spec.js
- extension/test/integration/fetch-payment-method.handler.spec.js
- extension/test/integration/kcp-make-payment.spec.js
- extension/test/integration/paypal-redirect-shopper.handler.spec.js
- notification/README.md
- notification/src/handler/notification/notification.handler.js
- notification/test/resources/notification.json
Related Issue: #63 
**Note**: cypress was not working in Travis for this I needed to update travis.yml: 95cd24c
Details: https://github.com/cypress-io/cypress/issues/4069
> Remove obsolete data from interface interactions

- extension/package-lock.json
- extension/package.json
- notification/package.json
> 🐸Split unit and integration test commands

- extension/Dockerfile
- extension/package-lock.json
- extension/package.json
- notification/Dockerfile
- notification/package-lock.json
- notification/package.json
#209 
Image size are not changed much, it was 146 MB now it's 163 MB (because nodejs 12 image size is bigger than nodejs 8)
https://nodejs.org/en/about/releases/
https://hub.docker.com/_/node/
> use official node alpine image and update from node 8 to node 12.18.0 LTS

- extension/src/lambda.js
- extension/test/unit/lambda.spec.js
Null check around `paymentResult.data`, which can be null if `paymentHandler` short circuits when not an adyen payment
> extension/src/lambda.js - handle nulls correctly

- extension/src/lambda.js
- extension/test/unit/lambda.spec.js
The response from a API Extension hosted in an AWS Lambda must contain a valid array for the `actions` property - i.e. undefined is not allowed
(This is an addition to a previous PR: https://github.com/commercetools/commercetools-adyen-integration/pull/297)
> fix: return empty actions when paymentHandler short-circuits

- extension/src/utils.js
- notification/src/utils/commons.js
When data comes in chunks then it is stored into an array.
It should be concatenated to reflect incoming data as a whole.
It behaves strangely when more than one chunk of data appears. `data` variable is somehow concatenated by comma(sic!) and breaks incoming JSON structure if comma appears in vulnerable part of JSON (e.g. after backslash `\,"`).
String concatenation is prepared according to following nodejs guide:
https://nodejs.org/es/docs/guides/anatomy-of-an-http-transaction/#put-it-all-together
> Concatenate obtained data before resolving promise

- extension/.eslintrc
- extension/docs/WebComponentsIntegrationGuide.md
- extension/src/validator/error-messages.js
- extension/src/validator/validator-builder.js
- extension/test/unit/payment-handler.spec.js
- extension/test/unit/validator-builder.spec.js
The problem: it is possible to create a payment with different values in `amountPlanned` and `makePaymentRequest custom field`. The problem is we're checking interface interaction for `makePaymentRequest`. If there's no interface interaction yet, we allow the value to be not matching. This leads to inconsistent payments that always fails.
Solution: `makePaymentRequest custom field` should be checked with `amountPlanned` if there's no interface interactions.
Fixes: https://github.com/commercetools/commercetools-adyen-integration/issues/461
> #461 Prevent on payment creation inconsistent amounts provided on makePaymentRequest and amountPlaned

- extension/docs/Refund.md
- extension/src/paymentHandler/payment-handler.js
- extension/src/paymentHandler/refund-payment.handler.js
- extension/test/integration/refund-payment.handler.spec.js
After the payment is authorized, it could take some time until the payment is captured. In Adyen, the Adyen payment has state `SentForSettle`.
During this time, there is no `Charge` transaction with state `Success` in the CTP payment. However, it is still possible to do (partial) refunds.
Therefore `Authorized` transaction in the CTP payment should also be taken into consideration when getting the `interactionId` field
> #399 take Authorized transaction into consideration when doing refund

- extension/test/e2e/credit-card-3ds-redirect.spec.js
As tests suddenly fail, I had a quick look and saw that credit card valid dates were already in the past. So I updated them.
> Update credit card date in e2e tests

- extension/package-lock.json
- extension/package.json
- extension/src/ctp.js
- notification/package-lock.json
- notification/package.json
- notification/src/utils/ctp.js
Addresses: #572 
-----------
Let's discuss this PR based on the user agent changes, normally package name is better to be unique.
Adyen `applicationInfo` will be 
```` JSON
{
"merchantApplication": {
"name": "commercetools-adyen-integration-extension",
"version": "7.0.1"
},
"externalPlatform": {
"name": "commercetools",
"integrator": "commercetools Professional Services"
}
}
````
CTP user agent will be:
````
http_useragent:commercetools-js-sdk Node.js/14.15.5 (linux; x64) 
commercetools-adyen-integration-notification/7.0.1 (+https://github.com/commercetools/commercetools-adyen-
integration; +ps-dev@commercetools.com)
````
> use unique names on the package.json

- extension/.prettierignore
- extension/docs/WebComponentsIntegrationGuide.md
- extension/src/service/web-component-service.js
- extension/test/integration/klarna-make-payment.spec.js
- extension/test/integration/make-payment.handler.spec.js
- notification/.prettierignore
- notification/docs/IntegrationGuide.md
- notification/src/utils/parser.js
- notification/test/integration/multitenancy.spec.js
- notification/test/integration/notification.handler.spec.js
- notification/test/resources/notification-refund-fail.json
- notification/test/resources/notification.json
- notification/test/unit/lambda.spec.js
- notification/test/unit/notification.controller.spec.js
- notification/test/unit/notification.handler.spec.js
Due to restrictions in the Adyen API, it's not allowed to have metadata key with length more than 20 characters and metadata values with more than 80 characters. In this PR, we fixed this problem.
> Shorten metadata.commercetoolsProjectKey name

- extension/test/e2e/credit-card-3ds-native.spec.js
**Description**
The end-to-end test cases are flaky. It may randomly fail and block the build.
**Hints**
Extend the web browser timeout for waiting for the response.
> Fix e2e test

- extension/src/paymentHandler/klarna-make-payment.handler.js
As described in #700 currently Klarna payment fails for custom shipping methods.
I can update this PR if decision is made to use `name` or `localizedDescription` for standard shipping methods instead of deprecated `description`. See docs related to this: https://docs.commercetools.com/api/projects/shippingMethods#shippingmethod
> Fix klarna custom shipping method description getter

- extension/src/validator/validator-builder.js
`amountInMakePaymentRequest` should be convert to Number before checking, because it comes from parsed string.
It is a fix for error:
```
{
"code": "InvalidField",
"message": "amountPlanned field must be the same as the amount in makePaymentRequest in the interface interactions or makePaymentRequest  in the custom field"
}
```
this PR is related to my opened issue: https://github.com/commercetools/commercetools-adyen-integration/issues/807
> Fix for validator-builder.js

- extension/test/e2e/klarna.spec.js
- extension/test/e2e/pageObjects/KlarnaPage.js
- extension/test/e2e/pageObjects/MakePaymentFormPage.js
**Situation**
We have e2e test for Klarna payment
**Complication**
Recently a new IBAN input field is added in Klarna page. It didn't exist before so we don't handle it in our web test, which cause e2e test failure in these days.
**Resolution**
Autofill the IBAN input field in e2e test
**Hints for reviewer**
- Add auto-filling for new IBAN input field.
- Enhance the error logging in klarna payment e2e test
- Change from `page.waitForTimeout(...)` to `frame.waitForSelector(...)` to ensure Klarna payment page is completely loaded
> Fix klarna e2e test

- .github/workflows/ci.yml
Replacing turnstyle with concurrency.
Successfully tested that functionality on my project:
https://github.com/HollowMan6/LZU-Auto-COVID-Health-Report/blob/d23c4ac83fd5ae770595c1fda8ad1d66b7ceaa89/.github/workflows/autoreport.yml#L2
Test result: 
Since I noticed that the `same-branch-only` is `false`, I didn't add `-${{ github.ref }}` in the group name.
Resolves #827 
Signed-off-by: Hollow Man <hollowman@hollowman.ml>
> Use the concurrency keyword to limit the ci concurrency

- extension/resources/web-components-payment-type.json
- extension/src/config/config.js
- extension/src/config/constants.js
- extension/src/paymentHandler/get-carbon-offset-costs.handler.js
- extension/src/paymentHandler/payment-handler.js
- extension/src/service/web-component-service.js
- extension/src/validator/error-messages.js
- extension/src/validator/validator-builder.js
- extension/test/unit/get-carbon-offset-costs.handler.spec.js
- extension/test/unit/validator-builder.spec.js
Overview: https://www.adyen.com/social-responsibility/impact#restore
Concept: Offset information will be requested through our adyen integration, integration user will set a custom field and we will call Adyen API and set it back to response custom field. This needs to be before the makePaymentRequest. 
PR addresses the offset calculation only. Integration tests and documentation will be added part of another task.
> add get-carbon-offset-costs.handler and cover it with unit tests

- extension/package.json
- extension/test/e2e/credit-card-3ds-native.spec.js
- extension/test/e2e/pageObjects/CreditCard3dsNativePage.js
I had a quick look and the only test that is constantly failing is extension/test/e2e/credit-card-3ds-native.spec.js with MasterCard.
The issue is the payment verification page for MasterCard 3D has changed and is now different from before. Therefore our selectors do not work anymore.
After disabling MasterCard tests are working again.
Suggestion: I would remove completely MasterCard from the 3D verification test and leave Visa there. For testing the flow it's enough. Having another credit card do not add much value comparing to the maintenance we have to do. WDYT?
> Disable test that has changed the flow

- extension/docs/HowToRun.md
See https://docs.commercetools.com/api/releases/2021-12-09-increased-maximum-timeout-for-payment-related-api-extensions
> Support does not need to be contacted anymore, 10 sec is the new limit for payment extensions

- extension/test/e2e/affirm.spec.js
- extension/test/e2e/credit-card-3ds-native.spec.js
- extension/test/e2e/e2e-test-utils.js
- extension/test/e2e/pageObjects/CreditCard3dsNativePage.js
- extension/test/e2e/pageObjects/RedirectPaymentFormPage.js
The problems:
- 3DS native now requires clientKey, so I added it. 
- Additionally somehow the test could not click on one button in the iframe anymore. I had to update the clicking mechanism to make it work.
- Affirm seems to be working fine, so there is no fix needed.
> Fix 3DS native test

- extension/test/e2e/fixtures/klarna-make-payment-form.html
- extension/test/e2e/pageObjects/KlarnaPage.js
klarna test were not working, it seems now klarna requires a otp step, which I added to test, used the test accounts documented by klarna: https://docs.klarna.com/resources/test-environment/sample-data/#germany, old ones were not working 🤷🏽
> fix klarna e2e test.

- extension/docs/HowToRun.md
- extension/test/e2e/fixtures/klarna-make-payment-form.html
- extension/test/e2e/pageObjects/KlarnaPage.js
- notification/docs/HowToRun.md
On one of the review: https://github.com/commercetools/commercetools-adyen-integration/pull/918#discussion_r808983409 we had a discussion and found out the existing documentation creates confusion, as it's grouped in a way that you can not understand what is the required values and optional ones, also the given examples with the values are defined with the not default values as it's better to suggest to use default values as it might be the better choice: https://github.com/commercetools/commercetools-adyen-integration/pull/918#discussion_r808985460
> change the structure of describing environment variables on how to run docs.

- extension/package-lock.json
- extension/package.json
- extension/test/unit/google-function.spec.js
- notification/index.googleFunction.js
- notification/index.lambda.js
- notification/package-lock.json
- notification/package.json
- notification/src/api/notification/notification.controller.js
- notification/src/server.js
- notification/src/utils/parser.js
- notification/test/unit/google-function.spec.js
- notification/test/unit/notification.controller.spec.js
According to these docs: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html, https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html I found out a way how to get the correct URL in AWS. However it's not tested yet in AWS.
> Update notification to parse aws url correctly

- extension/test/e2e/pageObjects/KlarnaPage.js
- notification/index.lambda.js
- notification/src/utils/parser.js
In order to get the URL path for AWS, it is necessary to use `rawPath` attr as documented in the link below.
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format
So I made this change in this PR.
> Update getting URL path for AWS

- extension/package-lock.json
- extension/package.json
- extension/src/init.js
- notification/package-lock.json
- notification/package.json
1) We have an issue with the docker image in the latest release(Since Es module changes are merged into master).
Fix the issue in the init file.
Issue: https://github.com/commercetools/commercetools-adyen-integration/issues/963
2) Setup-resources in [package.json](https://github.com/commercetools/commercetools-adyen-integration/pull/964/files#diff-0e96fc4c0e4b663545725cc50af120099cb873ea9e3f16eee74d074e39be13feL23) was using require to call setup.js file and that is no more supported. Hence I have added a new library `run-func` which runs the function from terminal instance.  
Issue : https://github.com/commercetools/commercetools-adyen-integration/issues/965
> Fix syntax issues in the init file.

- extension/package-lock.json
- extension/package.json
- extension/test/e2e/pageObjects/KlarnaPage.js
- notification/package.json
Klarna e2e test suddenly stops working. It was not waiting for the modal window to display in the klarna payment page and it just immediately clicks the button. I found out that it's because we were not waiting for the button to be visible. I added the waiting for visibility option.
It is not clear why it was working before. I tried to downgrade to version 14, but the problem was still there. What I could notice is that it takes couple of seconds to load the modal window in Klarna. Maybe it's because now it takes more time to load the modal window than before when the modal window popped up immediately?
> Fix klarna test

- extension/package-lock.json
- extension/package.json
- notification/package-lock.json
- notification/package.json
- renovate.json
serialize-error dep was not updated because the newest version needs ECMAScript modules. Since we recently update everything to ECMAScript modules, we could now also update serialize-error.
> Update serialize-error dep

- .github/workflows/ci.yml
- extension/src/utils.js
- extension/test/unit/payment.controller.spec.js
I added name of the module (extension) to make the error clear that it comes from the extension module.
Boy-scout change: I also put back the dependency between build of extension and notification modules. Now the notification module will wait for build from the extension module to complete before it starts. To be frank the 2 modules do not depend on each other, but I see that the builds are failing randomly, so maybe that could be a problem. Let's see if it helps.
> Improve error logging

- docs/adr/0008-idempotency-key.md
- extension/.prettierignore
- extension/docs/ManualCapture.md
- extension/docs/Refund.md
- extension/resources/payment-transaction-type.json
- extension/src/ctp.js
- extension/src/paymentHandler/make-payment.handler.js
- extension/src/paymentHandler/manual-capture.handler.js
- extension/src/paymentHandler/payment-utils.js
- extension/src/paymentHandler/refund-payment.handler.js
- extension/src/service/web-component-service.js
- extension/test/integration/affirm-make-payment.spec.js
- extension/test/integration/amount-updates.handler.spec.js
- extension/test/integration/get-carbon-offset-costs.handler.spec.js
- extension/test/integration/get-payment-methods.handler.spec.js
- extension/test/integration/klarna-make-payment.spec.js
- extension/test/integration/make-payment.handler.spec.js
- extension/test/integration/manual-capture.spec.js
- extension/test/integration/refund-payment.handler.spec.js
- extension/test/test-utils.js
- extension/test/unit/get-carbon-offset-costs.handler.spec.js
- extension/test/unit/get-payment-methods.handler.spec.js
- extension/test/unit/make-lineitems-payment.handler.spec.js
- extension/test/unit/make-payment-with-splits.handler.spec.js
- extension/test/unit/make-payment.handler.spec.js
- extension/test/unit/multitenancy.spec.js
- extension/test/unit/payment-handler-lineItems.spec.js
- extension/test/unit/refund-payment.handler.spec.js
- extension/test/unit/submit-payment-details.handler.spec.js
- notification/.prettierignore
Related doc from adyen: https://docs.adyen.com/development-resources/api-idempotency
Boy-scout change: I also tried to fix one frequently failing test: https://github.com/commercetools/commercetools-adyen-integration/runs/7915704142?check_suite_focus=true#step:11:247
Addressing the issue: https://github.com/commercetools/commercetools-adyen-integration/issues/930
> #930 add idempotency key field

- extension/docs/ManualCapture.md
Fix the wrong text in manual capture documentation which was written as refund in some area.
> Fix manual capture document

- extension/package-lock.json
- extension/package.json
- extension/src/paymentHandler/submit-payment-details.handler.js
- extension/test/unit/submit-payment-details.handler.spec.js
- notification/package-lock.json
- notification/package.json
This PR prevents creating a new transaction when a transaction with the same interactionId already exists.
> Check if transaction exists before creating an update action

- extension/package.json
Remove `--exit` mocha param as it is redundant: https://mochajs.org/#-exit
> Remove mocha exit param

- extension/test/e2e/pageObjects/AffirmPage.js
- notification/docs/HowToRun.md
- notification/docs/IntegrationGuide.md
- notification/src/config/config.js
- notification/src/config/init/ensure-adyen-webhook.js
- notification/src/setup.js
- notification/test/unit/config.spec.js
This PR adds an ensure functionality for adyen webhooks.
HMAC is not added yet in this PR. It will be done in the next PR.
The part `ensuring fallback for metadata` is not possible with this feature. The reason is there is no specified connection between the Adyen project and CTP project and thus the URL cannot be ensured automatically. The correct fallback URL must be created by the user.
> Notification management api

- docs/FAQ.md
- docs/adr/0002-matching-adyen-notification.md
- docs/adr/0011-matching-adyen-notification.md
- extension/src/paymentHandler/make-payment.handler.js
- extension/src/paymentHandler/payment-utils.js
- extension/src/paymentHandler/submit-payment-details.handler.js
- extension/test/e2e/pageObjects/AffirmPage.js
- extension/test/e2e/pageObjects/PaypalPopupPage.js
- extension/test/integration/make-payment.handler.spec.js
- extension/test/unit/make-payment-with-splits.handler.spec.js
- extension/test/unit/make-payment.handler.spec.js
- extension/test/unit/submit-payment-details.handler.spec.js
- notification/docs/IntegrationGuide.md
- notification/src/handler/notification/notification.handler.js
- notification/src/utils/ctp.js
- notification/test/integration/multitenancy.spec.js
- notification/test/integration/notification.handler.spec.js
- notification/test/test-utils.js
- notification/test/unit/ctp-client-mock.js
- notification/test/unit/notification.controller.spec.js
- notification/test/unit/notification.handler.spec.js
**Extension**
- Set the `pspReference` to payment key if it exists in the response in making payment and submitting additional payment details. If it is not found within response, put `merchantReference` as payment key.
**Notification**
- Get payment by original reference or psp reference or merchant reference. Not only by merchant reference
- Update the payment key by pspReference if notification represents a successful authorization and the old transaction is not yet successful.
> Fix notification payment lookup

- extension/src/config/constants.js
- extension/src/service/web-component-service.js
- extension/test/unit/refund-payment.handler.spec.js
Fixes : #1052 
- When we receive the response from Adyen API call, now we check if the response is JSON format. If it isn't, we would put it as plain text response into `InterfaceInteractions` so that user would know what actually happen.
- Fix other refund unit test cases since mocking response for payment API call is not applicable.
> Handle non-JSON response

- notification/src/utils/logger.js
Fixed typo when getting `logLevel` from config to override default `info` level.
Ran notification instance and checked if `logLevel` is passed correctly.
> Fix setting logLevel from config in notification service

- extension/src/api/payment/payment.controller.js
- extension/src/server.js
- extension/src/utils.js
- extension/test/unit/payment.controller.spec.js
- notification/src/api/notification/notification.controller.js
- notification/src/handler/notification/notification.handler.js
- notification/src/server.js
- notification/test/unit/notification.controller.spec.js
- notification/test/unit/notification.handler.spec.js
The motivation behind this PR is that I would like to observe better what's going on in the extension and notification applications. I would like to track a whole request path by request id and have a response time.
In my PR I inject a logger instead of importing it from utils. The injected logger has a context of the request, it contains information about the requesting path, used HTTP method, and request id. In my opinion, it's better to have a context instead of a raw logger without anything.
Also, I changed the notification handler to accept an object. This approach is more flexible in case of adding new things in the future and it provides more context for the developer, especially for the boolean values, now you don't have to remember the order of the arguments. 
Not much to test …
> feat: more logs for extension and notification apps
